<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\PostStatus;
use App\Models\Page;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Page>
 */
class PageFactory extends Factory
{
    public function definition(): array
    {
        return [
            'user_id' => User::factory(),
            'title' => $this->faker->sentence(4),
            // slug auto-generated by HasSlug on save
            'excerpt' => $this->faker->paragraph(),
            'body_html' => '<p>'.$this->faker->paragraphs(2, true).'</p>',
            'seo_title' => null,
            'seo_description' => null,
            'status' => PostStatus::Draft,
            'published_at' => null,
            'sort_order' => 0,
            'is_homepage' => false,
            'is_comments_enabled' => true,
            'meta' => [],
        ];
    }

    public function published(): static
    {
        return $this->state(fn (): array => [
            'status' => PostStatus::Published,
            'published_at' => now()->subHour(),
        ]);
    }

    public function homepage(): static
    {
        return $this->state(fn (): array => ['is_homepage' => true]);
    }
}
